---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        env:
        - name: LD_CSRF_TRUSTED_ORIGINS
          value: "{{ .Values.ingressProtocol }}{{ .Values.ingressHostName }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: www
        volumeMounts:
        - mountPath: /etc/linkding/data
          name: {{ .Values.appName }}-volume
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.appName }}-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClass }}
      resources:
        requests:
          storage: {{ .Values.storageSize }}