apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.immich.immich.persistence.library.existingClaim}}-pv"
spec:
  capacity: 
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/Storage/apps/immich/photos
    server: "fs1.sancaktar.net"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.immich.immich.persistence.library.existingClaim}}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: "{{ .Values.immich.immich.persistence.library.existingClaim}}-pv"