---
immich:

  immich:
    persistence:
      # Main data store for all photos shared between different components.
      library:
        # Automatically creating the library volume is not supported by this chart
        # You have to specify an existing PVC to use
        existingClaim: immich-pvc-claim

  postgresql:
    enabled: true
    global:
      storageClass: mayastor
    primary:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
  redis:
    enabled: true

  microservices:
    persistence:
      geodata-cache:
        type: pvc
        accessMode: ReadWriteMany
        storageClass: mayastor

  machine-learning:
    persistence:
      cache:
        type: pvc
        storageClass: mayastor

  proxy:
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: photos.sancaktar.net
            paths:
              - path: "/"
