---
immich:
  immich:
    persistence:
      # Main data store for all photos shared between different components.
      library:
        # Automatically creating the library volume is not supported by this chart
        # You have to specify an existing PVC to use
        existingClaim: immich-pvc-claim
  env:
    DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.existingSecret }}"
  postgresql:
    image:
      debug: true
    primary:
      extendedConfiguration: |-
        huge_pages = off
        enabled: true
      extraVolumeMounts:
        - name: pg-sample-config
          mountPath: /opt/bitnami/postgresql/share/postgresql.conf.sample
          subPath: postgresql.conf.sample
      extraVolumes:
        - configMap:
            name: pg-sample-config
          name:  pg-sample-config
    extraDeploy:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: pg-sample-config
        data:
          postgresql.conf.sample: |-
            huge_pages = off
    global:
      storageClass: mayastor
      postgresql:
        auth:
          existingSecret: immich-postgresql
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: password
    primary:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
  redis:
    enabled: true

  microservices:
    persistence:
      geodata-cache:
        type: pvc
        accessMode: ReadWriteMany
        storageClass: mayastor

  machine-learning:
    persistence:
      cache:
        type: pvc
        storageClass: mayastor

  proxy:
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: photos.sancaktar.net
            paths:
              - path: "/"
